# .gitlab-ci.yml
default:
  image: node:20

stages:
  - test

test:
  stage: test
  script:
    - echo "Hello world"
    - npm ci --cache .npm --prefer-offline
    - npm run mocha

  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm/
